### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [gnitetsky/flexbox-template-init-project#1]
ошибки валидации
![image](https://user-images.githubusercontent.com/8464662/54076098-09f15900-42b0-11e9-8be3-a996a60ee34c.png)

слишком большой уровень вложенных селекторов.
![image](https://user-images.githubusercontent.com/8464662/54076138-9f8ce880-42b0-11e9-80f9-4ec827f63da1.png)

правильным является селектор 1уровня, максимум 2го,
в виде исключения, на события можно сделать 3.

![image](https://user-images.githubusercontent.com/8464662/54076174-1924d680-42b1-11e9-8fd4-573a732df919.png)
Существовало много методологий, но сейчас только БЭМ является стандартом дефакто для именования классов.
в предложенном варианте именования классов структура кода читается плохо, разделение разметки на блоки и элементы - отсутствует.

![image](https://user-images.githubusercontent.com/8464662/54076220-bf70dc00-42b1-11e9-861d-84b8968bdea1.png)
этот элемент не является самым главным на странице и использование тега h1 здесь не обосновано.

**Comment by gnitetsky** [comment]
fixed bugs
